# Generated by Django 4.2.1 on 2023-06-03 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0002_rename_personal_employee_designation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="name", new_name="title",
        ),
        migrations.AddField(
            model_name="project",
            name="employee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="resume_app.employee",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="role_responsibilities",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="technology_used",
            field=models.CharField(max_length=100),
        ),
    ]
